TrajectoryPlannerROS:
  max_vel_x: 0.35
  min_vel_x: 0.1
  max_rotational_vel: 3.5
  min_in_place_rotational_vel: 0.4

  acc_lim_th: 2.0
  acc_lim_x: 4.0
  
  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.1
  meter_scoring: true
 

  holonomic_robot: false
