#Author: Brian Pappas
#Last Update: 6-20-2013

TrajectoryPlannerROS:
  max_vel_x: 0.35
  min_vel_x: 0.25
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.4

  acc_lim_th: 2.0
  acc_lim_x: 2.0
  
  dwa: true
  sim_granularity: 0.01
  controller_frequency: 15
  
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.3
  meter_scoring: true
  sim_time: 1.5
 

  holonomic_robot: false
