#Author: Brian Pappas
#Last Update: 6-20-2013

local_costmap:
  global_frame: /map
  robot_base_frame: base_footprint
  update_frequency: 2.0
  publish_frequency: 0.3
  static_map: true
  rolling_window: false
  
